services:


  vesta-server:
    image: ghcr.io/mahmoudamouni/vesta-server:latest
    container_name: vesta-server
    ports:
      - "8000:80"
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: vestapp
      DB_USERNAME: root
      DB_PASSWORD: ""
    volumes:
      - ./server-storage:/var/www/html/storage
    command: sh -c "php artisan migrate --force && apache2-foreground"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: vesta-mysql
    restart: always
    environment:
      MYSQL_DATABASE: vestapp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
