name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.host_name }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          script: |
            cd /var/www/html/VestaServer
            git pull origin main

            composer install --no-interaction --no-progress --optimize-autoloader

            sudo chgrp -R www-data storage bootstrap/cache
            sudo chmod -R ug+rwx storage bootstrap/cache

            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache

            php artisan migrate --force
